const HOLIDAYS_ACTION_PREFIX = "holidays";

export const HOLIDAYS_ENDPOINT_URL = "/holidays";
export const FETCH_HOLIDAYS_ACTION_PREFIX = `${HOLIDAYS_ACTION_PREFIX}/fetch`;

export const SAVE_HOLIDAYS_ACTION_PREFIX = `${HOLIDAYS_ACTION_PREFIX}/save`;

export const GENERATE_DEFAULT_HOLIDAYS_URL = `${HOLIDAYS_ENDPOINT_URL}/default?year=`

