const PRESENCE_ENDPOINT = "/api/v2/presence-confirmations"
const PRESENCE_ACTION_PREFIX = "presence"

export const FETCH_MY_PRESENCE_CONFIRMATIONS_URL = PRESENCE_ENDPOINT
export const FETCH_MY_PRESENCE_CONFIRMATIONS_ACTION_PREFIX = `${PRESENCE_ACTION_PREFIX}/fetch/my`

export const FETCH_USERS_PRESENCE_CONFIRMATIONS_URL = PRESENCE_ENDPOINT
export const FETCH_USERS_PRESENCE_CONFIRMATIONS_ACTION_PREFIX = `${PRESENCE_ACTION_PREFIX}/fetch/all`

export const ADD_PRESENCE_CONFIRMATION_URL = PRESENCE_ENDPOINT
export const ADD_PRESENCE_CONFIRMATION_ACTION_PREFIX = `${PRESENCE_ACTION_PREFIX}/add`