const APP_INFO_ENDPOINT = "/api/v2/info"
const APP_INFO_ACTION_PREFIX = "app-info"

export const FETCH_APP_INFO_URL = APP_INFO_ENDPOINT
export const FETCH_APP_INFO_ACTION_PREFIX = `${APP_INFO_ACTION_PREFIX}/fetch`
