const USER_PREFERENCES_ENDPOINT = "/api/v2/users/preferences/"
const USER_PREFERENCES_ACTION_PREFIX = "user-preferences"

export const FETCH_USER_WORKING_HOURS_PREFERENCES_URL = `${USER_PREFERENCES_ENDPOINT}/working-hours`
export const FETCH_USER_WORKING_HOURS_PREFERENCES_ACTION_PREFIX = `${USER_PREFERENCES_ACTION_PREFIX}/working-hours/fetch`

export const CHANGE_USER_WORKING_HOURS_PREFERENCES_URL = `${USER_PREFERENCES_ENDPOINT}/working-hours`
export const CHANGE_USER_WORKING_HOURS_PREFERENCES_ACTION_PREFIX = `${USER_PREFERENCES_ACTION_PREFIX}/working-hours/change`
