const REQUESTS_ENDPOINT = "/absence-requests";
const REQUESTS_ACTION_PREFIX = "requests";

const ACCEPTANCES_ENDPOINT = "/absence-request-acceptances";
const ACCEPTANCE_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/acceptances`;

export const FETCH_MY_REQUESTS_URL = `${REQUESTS_ENDPOINT}/requester/me`;
export const FETCH_MY_REQUESTS_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/fetch/my`;

export const FETCH_COMPANY_REQUESTS_URL = `${REQUESTS_ENDPOINT}`;
export const FETCH_COMPANY_REQUESTS_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/fetch/company`;

export const FETCH_WORKER_REQUESTS_HISTORY_URL = `${REQUESTS_ENDPOINT}`;
export const FETCH_WORKER_REQUESTS_HISTORY_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/fetch/worker`;

export const CHANGE_REQUEST_STATUS_URL = `${REQUESTS_ENDPOINT}`;
export const CHANGE_REQUEST_STATUS_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/change-status`;

export const CREATE_REQUEST_URL = `${REQUESTS_ENDPOINT}`;
export const CREATE_REQUEST_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/create-request`;

export const FETCH_ACCEPTANCES_PENDING_URL = `${ACCEPTANCES_ENDPOINT}`;
export const FETCH_ACCEPTANCES_PENDING_ACTION_PREFIX = `${ACCEPTANCE_ACTION_PREFIX}/fetch/pending`;

export const FETCH_ACCEPTANCES_HISTORY_URL = `${ACCEPTANCES_ENDPOINT}/history`;
export const FETCH_ACCEPTANCES_HISTORY_ACTION_PREFIX = `${ACCEPTANCE_ACTION_PREFIX}/fetch/history`;

export const CHANGE_ACCEPTANCE_STATUS_URL = `${ACCEPTANCES_ENDPOINT}`;
export const CHANGE_ACCEPTANCE_STATUS_ACTION_PREFIX = `${ACCEPTANCE_ACTION_PREFIX}/change-status`;
