const REQUESTS_ENDPOINT = "/api/v2/absence-requests";
const REQUESTS_ACTION_PREFIX = "requests";

const ACCEPTANCES_ENDPOINT = "/api/v2/absence-request-acceptances";
const ACCEPTANCE_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/acceptances`;

export const FETCH_MY_REQUESTS_URL = `${REQUESTS_ENDPOINT}/requester/me`;
export const FETCH_MY_REQUESTS_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/fetch/my`;

export const FETCH_COMPANY_REQUESTS_URL = `${REQUESTS_ENDPOINT}`;
export const FETCH_COMPANY_REQUESTS_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/fetch/company`;

export const CHANGE_REQUEST_STATUS_URL = `${REQUESTS_ENDPOINT}`;
export const CHANGE_REQUEST_STATUS_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/change-status`;

export const CREATE_REQUEST_URL = `${REQUESTS_ENDPOINT}`;
export const CREATE_REQUEST_ACTION_PREFIX = `${REQUESTS_ACTION_PREFIX}/create-request`;

export const FETCH_ACCEPTANCES_URL = `${ACCEPTANCES_ENDPOINT}`;
export const FETCH_ACCEPTANCES_ACTION_PREFIX = `${ACCEPTANCE_ACTION_PREFIX}/fetch`;

export const CHANGE_ACCEPTANCE_STATUS_URL = `${ACCEPTANCES_ENDPOINT}`;
export const CHANGE_ACCEPTANCE_STATUS_ACTION_PREFIX = `${ACCEPTANCE_ACTION_PREFIX}/change-status`;
