package info.fingo.urlopia.request.absence;

public enum SpecialAbsenceReason {
    ADDITIONAL_CARE_ALLOWANCE_PANDEMIC,
    BLOOD_DONATION_PANDEMIC,
    BLOOD_DONATION,
    DELEGATION,
    UNPAID_LEAVE,
    PARENTAL_LEAVE,
    MATERNITY_LEAVE,
    PATERNITY_LEAVE,
    SICK_LEAVE_EMPLOYEE,
    SICK_LEAVE_CHILD,
    UNEXCUSED,
    CHILDCARE,
    CHILDCARE_FOR_14_YEARS_OLD,
    WRONG,
    OTHER
}

