const USERS_VACATIONS_ENDPOINT_PREFIX = "/api/v2/calendar/users/"
const USERS_VACATIONS_ENDPOINT_POSTFIX = "/vacations"
const USERS_VACATIONS_ACTION_PREFIX = "users-vacations"

export const FETCH_USERS_VACATIONS_ENDPOINT_PREFIX = USERS_VACATIONS_ENDPOINT_PREFIX
export const FETCH_USERS_VACATIONS_ENDPOINT_POSTFIX = USERS_VACATIONS_ENDPOINT_POSTFIX
export const FETCH_USERS_VACATIONS_ACTION_PREFIX = `${USERS_VACATIONS_ACTION_PREFIX}/fetch`
