DROP TABLE IF EXISTS history_logs;

DROP TABLE IF EXISTS acceptances;

DROP TABLE IF EXISTS requests;

DROP TABLE IF EXISTS users_teams;

DROP TABLE IF EXISTS teams;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS holidays;