const ABSENCE_HISTORY_ENDPOINT = "/api/v2/absence-history"
const ABSENCE_HISTORY_ACTION_PREFIX = "absence-history"

export const FETCH_MY_ABSENCE_HISTORY_URL = `${ABSENCE_HISTORY_ENDPOINT}/me?year=`
export const FETCH_MY_ABSENCE_HISTORY_ACTION_PREFIX = `${ABSENCE_HISTORY_ACTION_PREFIX}/fetch/my`

export const FETCH_USER_ABSENCE_HISTORY_URL = `${ABSENCE_HISTORY_ENDPOINT}`
export const FETCH_USER_ABSENCE_HISTORY_PREFIX = `${ABSENCE_HISTORY_ACTION_PREFIX}/fetch/user`

