const ABSENCE_HISTORY_ACTION_PREFIX = 'absence-history';

export const FETCH_ABSENCE_HISTORY_URL = '/api/v2/absence-history';
export const FETCH_ABSENCE_HISTORY_ACTION_PREFIX = `${ABSENCE_HISTORY_ACTION_PREFIX}/fetch/history`;

export const FETCH_USER_RECENT_ABSENCE_HISTORY_URL = '/api/users';
export const FETCH_USER_RECENT_ABSENCE_HISTORY_URL_POSTFIX = '/days/recent';
export const FETCH_USER_RECENT_ABSENCE_HISTORY_ACTION_PREFIX = `${ABSENCE_HISTORY_ACTION_PREFIX}/fetch/recent`;
